name: TournamentHubRacer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "VITE_WALLETCONNECT_PROJECT_ID=${{ secrets.WALLETCONNECT_PROJECT_ID}}" && echo "VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }}">> .env.local
      - name: Build docker image
        run: docker build -t nishan2030/tournamenthubracer .
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD}}
      - name: Publish image to docker hub
        run: docker push nishan2030/tournamenthubracer:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Login to docker hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD}}

    - name: Clean up unused Docker resources
      run: docker system prune -af --volumes

    - name: Delete old container
      run: docker rm -f tournamenthubracer-container
      
    - name: Pull image from docker hub
      run: docker pull nishan2030/tournamenthubracer:latest

    - name: Run docker container
      run: docker run -d -p 80:80 --name tournamenthubracer-container nishan2030/tournamenthubracer
